/**
 * OrderEvent prototype-store entity. Append-only per Daniel's strict
 * lifecycle-evidence posture (trade_lifecycle_contract.md:464). Once
 * appended, an OrderEvent row is immutable; the entity exposes no
 * mutation path.
 *
 * Frontend MUST NEVER append OrderEvents in production. Writers are
 * Trade Manager, Exec Gateway, reconciler, broker webhooks/pollers, and
 * operator tools. This entity exists for fixture seeding and dual-read.
 *
 * Daniel's PK is composite (order_id, occurred_at, event_id). The
 * frontend mirror uses `eventId` as the prototype-store key — `eventId`
 * is UUIDv4 in practice, generated by the writer, and is globally unique.
 * A second append with the same `eventId` throws.
 */
import { kvStore, makePrototypeMeta, type PrototypeMeta } from "../store";
import type { OrderEvent } from "../../sec203a/order-events";

export interface StoredOrderEvent extends OrderEvent {
  /** Standard prototype metadata. Daniel has no equivalent field. */
  bffMeta: PrototypeMeta;
}

const events = kvStore<StoredOrderEvent>("order-events");

// ─── Lookups ────────────────────────────────────────────────────────────────

export async function getOrderEvent(
  eventId: string,
): Promise<StoredOrderEvent | null> {
  return events.get(eventId);
}

export async function listOrderEventsForOrder(
  orderId: string,
): Promise<StoredOrderEvent[]> {
  const all = await events.list();
  return all
    .map((e) => e.value)
    .filter((ev) => ev.orderId === orderId)
    .sort((a, b) => a.occurredAt.localeCompare(b.occurredAt));
}

export async function listOrderEventsForCorrelation(
  correlationId: string,
): Promise<StoredOrderEvent[]> {
  const all = await events.list();
  return all
    .map((e) => e.value)
    .filter((ev) => ev.correlationId === correlationId)
    .sort((a, b) => a.occurredAt.localeCompare(b.occurredAt));
}

// ─── Append-only write ──────────────────────────────────────────────────────

/**
 * Append a single OrderEvent. Rejects if an event with the same `eventId`
 * already exists. There is no `updateOrderEvent` / `patchOrderEvent` /
 * `deleteOrderEvent` — OrderEvents are evidence and cannot be edited.
 */
export async function appendOrderEvent(args: {
  event: OrderEvent;
}): Promise<StoredOrderEvent> {
  const stored: StoredOrderEvent = {
    ...args.event,
    bffMeta: makePrototypeMeta(args.event.correlationId ?? args.event.eventId),
  };
  const ok = await events.putIfAbsent(args.event.eventId, stored);
  if (!ok) {
    throw new Error(
      `order event ${args.event.eventId} already exists — OrderEvents are append-only`,
    );
  }
  return stored;
}
