// Counsel-confirmed hero copy (2026-05-29). Keep neutral and non-promissory.
export const landingCopy = {
  hero: {
    headline: "A policy-bound trading platform for U.S. investors.",
    subheadline:
      "Model-driven recommendations, investor-defined execution limits, exception review, and records in one auditable product experience.",
    primaryCta: "Check Eligibility",
    secondaryCta: "Explore Demo",
  },
  trustRow: {
    items: [
      {
        title: "Broker-held custody",
        description: "Your assets stay at your broker. ReFi never holds funds.",
      },
      {
        title: "Software-generated recommendations",
        description:
          "Personalized recommendations generated by our models based on your profile.",
      },
      {
        title: "Clear guardrails",
        description: "Every action is compliance-checked before execution.",
      },
      {
        title: "Full records",
        description:
          "A complete record of every recommendation, decision, and execution.",
      },
    ],
  },
  howItWorks: {
    heading: "How it works",
    steps: [
      {
        number: "01",
        title: "Check eligibility",
        description: "Confirm your state of residence and US-person status.",
      },
      {
        number: "02",
        title: "Verify your email and connect your broker",
        description:
          "Verify your email address to create your account, then link your brokerage account. Connecting a wallet is optional.",
      },
      {
        number: "03",
        title: "Receive recommendations",
        description:
          "Software-generated, personalized investment recommendations delivered through the platform.",
      },
    ],
  },
} as const;
