// Headlines pending counsel sign-off on advisory copy (Q1 resolved; copy review in progress)
export const landingCopy = {
  hero: {
    headline: '[Headline — counsel review in progress]',
    subheadline: '[Subheadline — counsel review in progress]',
    primaryCta: 'Check Eligibility',
    secondaryCta: 'Explore Demo',
  },
  trustRow: {
    items: [
      {
        title: 'Broker-held custody',
        description: 'Your assets stay at your broker. ReFi never holds funds.',
      },
      {
        title: 'Software-generated recommendations',
        description: 'Personalized recommendations generated by our models based on your profile.',
      },
      {
        title: 'Clear guardrails',
        description: 'Every action is compliance-checked before execution.',
      },
      {
        title: 'Full records',
        description: 'A complete record of every recommendation, decision, and execution.',
      },
    ],
  },
  howItWorks: {
    heading: 'How it works',
    steps: [
      {
        number: '01',
        title: 'Check eligibility',
        description: 'Confirm your state of residence and US-person status.',
      },
      {
        number: '02',
        title: 'Connect your wallet and broker',
        description: 'Sign in with your Ethereum wallet and link your brokerage account.',
      },
      {
        number: '03',
        title: 'Receive recommendations',
        description: 'Software-generated, personalized investment recommendations delivered through the platform.',
      },
    ],
  },
} as const;
