import { baseConfig } from "@refi/config/eslint";

export default [
  ...baseConfig,
  {
    // Generated by openapi-typescript via `pnpm generate`. Not source code.
    ignores: ["src/generated/**"],
  },
];
